name: Build and test
on: push
jobs:
  run_tests:
    name: Run all tests
    runs-on: macOS-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Restore packages
        run: "flutter pub get"
      - name: Run tests
        run: "flutter test"
