name: Test and upload
on: push
jobs:
  test_and_upload:
    name: Test and upload to Firebase
    runs-on: macOS-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Restore packages
        run: "flutter pub get"
      - name: Run tests
        run: "flutter test"
      - name: Build Android apk
        run: flutter build apk
      - name: Upload APK 
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: my_testers
          file: build/app/outputs/flutter-apk/app-release.apk
